// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// covert_search
void covert_search(NumericVector x, NumericVector trials_, NumericVector dpmap_, NumericVector prior_, NumericVector seed_);
RcppExport SEXP _visualsearch_covert_search(SEXP xSEXP, SEXP trials_SEXP, SEXP dpmap_SEXP, SEXP prior_SEXP, SEXP seed_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type trials_(trials_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dpmap_(dpmap_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_(prior_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type seed_(seed_SEXP);
    covert_search(x, trials_, dpmap_, prior_, seed_);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_visualsearch_covert_search", (DL_FUNC) &_visualsearch_covert_search, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_visualsearch(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
