// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// covert_search_dp
int covert_search_dp(double trials, NumericVector dpmapR, NumericVector priorhR, double seed);
RcppExport SEXP _testcpp_covert_search_dp(SEXP trialsSEXP, SEXP dpmapRSEXP, SEXP priorhRSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type trials(trialsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dpmapR(dpmapRSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type priorhR(priorhRSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(covert_search_dp(trials, dpmapR, priorhR, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_testcpp_covert_search_dp", (DL_FUNC) &_testcpp_covert_search_dp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_testcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
