# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

covert_search <- function(x, trials_, dpmap_, prior_, seed_) {
    invisible(.Call(`_visualsearch_covert_search`, x, trials_, dpmap_, prior_, seed_))
}

