# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(trials_, seed_) {
    .Call(`_visualsearch_timesTwo`, trials_, seed_)
}

