# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

covert_search_dp <- function(trials, dpmapR, priorhR, seed) {
    .Call(`_testcpp_covert_search_dp`, trials, dpmapR, priorhR, seed)
}

